added create from path
Ivshti/enginefs pull request #4
Opened 2017-03-01 10:15 UTC by kanekotic

2017-03-01 11:39 UTC, Ivshti requested changes

2017-03-01 11:39 UTC, Ivshti commented on enginefs.js
> +        var torrent = fs.readFileSync(req.body.from)
why not async?

also, parse-torrent-file does take a file path, so you don't need `fs` at all. that's why i suggested it

2017-03-02 12:41 UTC, kanekotic commented on enginefs.js
> +        var torrent = fs.readFileSync(req.body.from)
@Ivshti `parse-torrent-file` requires to read the file, it does not allow just use the path. maybe something changed from previous versions. 
the documentation shows a use very similar to what i have done.

https://github.com/feross/parse-torrent-file

2017-03-05 19:36 UTC, Ivshti reviewed
check the comments, otherwise gtg

2017-03-05 19:36 UTC, Ivshti commented on .gitignore
> + @kanekotic
what's that mess? :)

2017-03-05 19:36 UTC, Ivshti commented on enginefs.js
> +        var parsed = parseTorrentFile(file)
maybe this should be in a try-catch, but i'm not sure; check if the underlying implementation can throw

2017-03-05 19:53 UTC, kanekotic commented on .gitignore
> + @kanekotic
0_0

2017-03-06 08:20 UTC, merged